const types = {
  GET_DASHBOARD_DATA: 'GET_DASHBOARD_DATA',
  API_START: 'API_START',
  API_END: 'API_END',
  ACCESS_DENIED: 'ACCESS_DENIED',
  API_ERROR: 'API_ERROR',
  API: 'API',
  SET_USER_JWT: 'SET_USER_JWT',
  SHOW_ERROR_MODAL: 'SHOW_ERROR_MODAL',
  SET_USERS_DATA: 'SET_USERS_DATA',
  SOME_TEST_DATA: 'SOME_TEST_DATA',
  SET_RANDOM_DATA: 'SET_RANDOM_DATA',
}

export default types;
